using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DataAccessLayer.Models
{
    public class Employee
    {
        public Guid Id { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeID { get; set; }
        public string Role { get; set; }
        public string DateOfBirth { get; set; }
        public string AadharNumber { get; set; }
        public string NameAsAadhar { get; set; }
        public string PANNumber { get; set; }
        public string NameAsPAN { get; set; }
        public string Gender { get; set; }
        public string ReportingManager { get; set; }
        public string Status { get; set; }
        public string DateOfJoining { get; set; }
        public string ProbationPeriod { get; set; }
        public string ConfirmationDate { get; set; }
        public string Email { get; set; }
        public string MobileNumber { get; set; }
        public string EmergencyContactName { get; set; }
        public string EmergencyContactNumber { get; set; }
        public string FatherName { get; set; }
        public string SpouseName { get; set; }
        public string Division { get; set; }
        public string CostCenter { get; set; }
        public string Grade { get; set; }
        public string Designation { get; set; }
        public string Location { get; set; }
        public string Department { get; set; }
        public string PaymentType { get; set; }
        public string BloodGroup { get; set; }
        public string MaritalStatus { get; set; }
        public string Address { get; set; }
        public string Street { get; set; }
        public string Area { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PinCode { get; set; }
        public string Country { get; set; }
        public string CurrentAddress { get; set; }
        public string CurrentStreet { get; set; }
        public string CurrentArea { get; set; }
        public string CurrentCity { get; set; }
        public string CurrentState { get; set; }
        public string CurrentPinCode { get; set; }
        public string CurrentCountry { get; set; }
        public string EmergencyName { get; set; }
        public string EmergencyMobileNumber { get; set; }
        public string EmergencyRelationship { get; set; }
        public string Qualification { get; set; }
        public string FromYear { get; set; }
        public string ToYear { get; set; }
        public string InstituteName { get; set; }
        public float Marks { get; set; }
        public int Gap { get; set; }
        public string Qualification1 { get; set; }
        public string FromYear1 { get; set; }
        public string ToYear1 { get; set; }
        public string InstituteName1 { get; set; }
        public float Marks1 { get; set; }
        public int Gap1 { get; set; }
        public string Qualification2 { get; set; }
        public string FromYear2 { get; set; }
        public string ToYear2 { get; set; }
        public string InstituteName2 { get; set; }
        public float Marks2 { get; set; }
        public int Gap2 { get; set; }
        public string CompanyName { get; set; }
        public string Designations { get; set; }
        public string EmploymentFromDate { get; set; }
        public string EmploymentToDate { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyName1 { get; set; }
        public string Designation1 { get; set; }
        public string EmploymentFromDate1 { get; set; }
        public string EmploymentToDate1 { get; set; }
        public string CompanyAddress1 { get; set; }
        public string CompanyName2 { get; set; }
        public string Designation2 { get; set; }
        public string EmploymentFromDate2 { get; set; }
        public string EmploymentToDate2 { get; set; }
        public string CompanyAddress2 { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankIFSCCode { get; set; }
        public string NameAsPerBankAccount { get; set; }
        public string AccountType { get; set; }
        public string PreviousPFAccountNumber { get; set; }
        public string UAN { get; set; }
        public string PassportNumber { get; set; }
        public string NameAsPassport { get; set; }
        public string ExpiryDate { get; set; }
        public string FamilyMemberName { get; set; }
        public string FamilyMemberRelationship { get; set; }
        public string FamilyMemberDOB { get; set; }
        public string FamilyMemberGender { get; set; }
        public string FamilyMemberBloodGroup { get; set; }
        public string FamilyMemberNationality { get; set; }
        public string FamilyMemberName1 { get; set; }
        public string FamilyMemberRelationship1 { get; set; }
        public string FamilyMemberDOB1 { get; set; }
        public string FamilyMemberGender1 { get; set; }
        public string FamilyMemberBloodGroup1 { get; set; }
        public string FamilyMemberNationality1 { get; set; }
        public string FamilyMemberName2 { get; set; }
        public string FamilyMemberRelationship2 { get; set; }
        public string FamilyMemberDOB2 { get; set; }
        public string FamilyMemberGender2 { get; set; }
        public string FamilyMemberBloodGroup2 { get; set; }
        public string FamilyMemberNationality2 { get; set; }
        public string EPFNomineeName { get; set; }
        public string EPFNomineePercent { get; set; }
        public string EPFNomineeName1 { get; set; }
        public string EPFNomineePercent1 { get; set; }
        public string EPFNomineeName2 { get; set; }
        public string EPFNomineePercent2 { get; set; }
        public string EPSNomineeName { get; set; }
        public string EPSNomineeName1 { get; set; }
        public string EPSNomineeName2 { get; set; }
        public string ESINomineeName { get; set; }
        public string ESINomineeName1 { get; set; }
        public string ESINomineeName2 { get; set; }
        public string GratuityNomineeName { get; set; }
        public string GratuityNomineePercentage { get; set; }
        public string GratuityNomineeName1 { get; set; }
        public string GratuityNomineePercentage1 { get; set; }
        public string GratuityNomineeName2 { get; set; }
        public string GratuityNomineePercentage2 { get; set; }
        public string AddressAttachment { get; set; }
        public string PresentAddressAttachment { get; set; }
        public string PreviousEmploymentAttachment { get; set; }
    }
}
